# Generated by Django 2.2.6 on 2022-08-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_webinar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namemodel',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
